### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lp353775321** [waketzheng/fastdfs-client-python#4]
<img width="1104" alt="企业微信截图_17319256048512" src="https://github.com/user-attachments/assets/d68f2f63-d392-468c-babc-bb51c91c085f">
已连接到 pydev 调试器(内部版本号 233.13135.95)Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\fastdfs_client\tracker_client.py", line 478, in tracker_query_storage_stor_without_group
    raise ResponseError(errmsg)
fastdfs_client.exceptions.ResponseError: [-] Error: Tracker response length is invaild, expect: 70, actual: 40
Exception ignored in: <function FastdfsClient.__del__ at 0x000002624B869FC0>
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\fastdfs_client\client.py", line 54, in __del__
  File "D:\Python310\lib\logging\__init__.py", line 1464, in debug
  File "D:\Python310\lib\logging\__init__.py", line 1734, in isEnabledFor
TypeError: 'NoneType' object is not callable

**Comment by lp353775321** [comment]
![image](https://github.com/user-attachments/assets/2e2dd672-4552-40dc-8b57-3deb7572c0bf)

**Comment by waketzheng** [comment]
应该是你服务端的配置问题，我把配置里的IP改成我的服务器，是可以上传成功的
